[package]
name = "siphasher"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "siphasher"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.29", default-features = false, features = ["derive", "nif_version_2_16"] }
siphasher = "0.3.10"
